import React from 'react'

const Contact = () => {
  return (
    <div>Contact</div>
  )
}

export default Contact

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
